import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    // title: "Create Next App",
    title: {
        template: "%s | Xite",
        default: "Xite_fan",
    },
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>{children}</body>
        </html>
    );
}
// Структура и компоненты
// Роутинг
// Layout
// Изображения
// Страница 404
// Полезные хуки
// usePathname
// useRouter
// useSearchParams
// useParams
// Клиентские vs серверные компоненты
// Server Actions (use server)
// Подгрузка данных:
// SSG
// SSR
// ISR
// SEO оптимизация
// Middleware
// Настройки конфига
// Сборка проекта
